#!/bin/sh -e
# Fakeroot and lein don't get along, so we set ownership after the fact.
chown -R root:root /usr/lib/disthene
chown disthene:disthene /var/log/disthene
chown -R disthene:disthene /etc/disthene
