#!/bin/bash

if [ -f /etc/default/disthene ]; then
    . /etc/default/disthene
fi

JAR="/usr/lib/disthene/disthene.jar"
OPTS=""

if [ -n "$DISTHENE_CONFIG_FILE" ]; then
  OPTS="$OPTS -c $DISTHENE_CONFIG_FILE"
fi

if [ -n "$DISTHENE_LOG_CONFIG_FILE" ]; then
  OPTS="$OPTS -l $DISTHENE_LOG_CONFIG_FILE"
fi

if [ -n "$DISTHENE_BLACKLIST_FILE" ]; then
  OPTS="$OPTS -b $DISTHENE_BLACKLIST_FILE"
fi

if [ -n "$DISTHENE_AGGREGATION_CONFIG_FILE" ]; then
  OPTS="$OPTS -a $DISTHENE_AGGREGATION_CONFIG_FILE"
fi

exec java $JAVA_OPTS -jar $JAR $OPTS
